### ISSUE TITLE
Custom YouTube URLs don't work

### ISSUE THREAD

**Issue by DoodlesEpic** [probablykasper/kadium#3] opened 2022-06-28 20:32 UTC
So YouTube has this option to create a custom URL once you pass a certain amount of subscribers such as `youtube.com/c/whateveryouwant` which quite a lot of creators use, I've noticed Kadium is throwing an error when trying to add a channel URL that is custom:

![image](https://user-images.githubusercontent.com/37254797/176278839-a96abfc1-8bc8-4d4a-8429-17e24875e210.png)

There are also VERY old channels that still have the /user/ route for their channels, such as PewDiePie @ https://www.youtube.com/user/PewDiePie/
Kadium will also throw the same error with this kind of URL. I guess it's something to do with how the URLs are being validated? Because adding a video from any channel that has this kind of URL does work and it's working good :)

**Comment by probablykasper** [comment] 2022-06-28 21:05
The issue is that YouTube's API has no way to deal with `/c/` and `/user/` urls, so that's why it's suggesting to use a video URL

**Comment by DoodlesEpic** [comment] 2022-06-28 21:28
Couldn't you try to get the channel ID from elsewhere? I know Invidious manages to find the channel ID from these custom URLs somehow.

**Comment by probablykasper** [comment] 2022-06-28 22:32
You definitely can, but not sure how easy/reliable that is

**Comment by DoodlesEpic** [comment] 2022-06-28 23:06
If you would be ok with scraping YouTube pages then you could open the website and grab the RSS feed for that channel, such as for PewDiePie: https://www.youtube.com/feeds/videos.xml?channel_id=UC-lHJZR3Gqxm24_Vd_AJ5Yw
But yeah apart from this I have no idea how to do it. Maybe using the YouTube API search could be an option too.

**Comment by probablykasper** [comment] 2022-06-29 00:45
The [ytextract](https://crates.io/crates/ytextract) create might work

**Comment by probablykasper** [comment] 2022-06-29 01:08
nvm, that crate wouldn't work

**Comment by probablykasper** [comment] 2022-06-29 03:32
I'll close this for now because I don't see myself implementing this anytime soon

**Closed as completed by probablykasper** 2022-06-29 03:32 UTC

**Comment by probablykasper** [comment] 2023-11-19 11:30
All channel URLs should work now. Including `/lacunarecs`, `/@lacunarecs`, `/c/lacunarecs`, `/user/lacunarecs` and even ones like `/lacunarecs/playlists` etc
