### ISSUE TITLE
youtube.com/user url's don't work

### ISSUE THREAD

**Issue by KraXen72** [probablykasper/kadium#5] opened 2022-07-12 15:52 UTC
some channels have a channel/ url by default from the https://www.youtube.com/feed/channels page, some use a /user which does not work.

**Comment by probablykasper** [comment] 2022-07-12 16:30
Duplicate of https://github.com/probablykasper/kadium/issues/3

**Closed as completed by probablykasper** 2022-07-12 16:30 UTC

**Comment by probablykasper** [comment] 2023-11-19 11:30
All channel URLs should work now. Including `/lacunarecs`, `/@lacunarecs`, `/c/lacunarecs`, `/user/lacunarecs` and even ones like `/lacunarecs/playlists` etc
